### ISSUE TITLE
can't find record with friendly id: "news"

### ISSUE THREAD

**Issue by pkawalya** [rauversion/rauversion-ror#6]
![Screenshot from 2024-02-20 07-27-19](https://github.com/rauversion/rauversion-ror/assets/1384372/e5386fe2-7e44-46c9-9c38-7e6e0f04810d)

ActiveRecord::RecordNotFound in ArticlesController#index
can't find record with friendly id: "news"
Extracted source (around line #15):

      .page(2).per(7)

    @category = Category.friendly.find("news")
    @news = Post.published.friendly.where(category_id: @category)
      .with_attached_cover
      .includes(user: {avatar_attachment: :blob})

Rails.root: /home/surpass/Documents/Projects/rauversion-ror-main

[Application Trace](http://localhost:3000/articles#) | [Framework Trace](http://localhost:3000/articles#) | [Full Trace](http://localhost:3000/articles#)
[app/controllers/articles_controller.rb:15:in `index'](http://localhost:3000/articles#)

**Comment by pkawalya** [comment]
Hello @michelson thank you for great. Kindly advise

**Comment by michelson** [comment]
Dis you run the seeds?

**Comment by pkawalya** [comment]
This worked. Thank you
